version: "3"
services:
  letheand:
    env_file:
      - .env
    volumes:
      - "chain:/home/lthn/data/chain"
    ports:
      - "48782:48782"
      - "48772:48772"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:48782/json_rpc" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
#    image: "registry.gitlab.com/lethean.io/blockchain/lethean:develop"
    build:
      context: .
      args:
        - RELEASE_TYPE=release-static
volumes:
  chain:
    external: true
