site_name: Lethean Builder Docs
site_dir: public
site_url: http://127.0.0.1:8000/
repo_url: https://gitlab.com/lthn.io/projects/chain/lethean
edit_uri: edit/master/docs/
repo_name: lthn/chain

theme:
  name: material
  custom_dir: docs/overrides
  features:
    - navigation.tabs
    - content.tabs.link

extra:
  generator: false
plugins:
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: true
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true

extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - meta
  - abbr
  - attr_list
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ⚓︎
